name: Automate GitHub Contributions

on:
  schedule:
    - cron: '0 12 */2 * *'  # Runs every alternate day at 12 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disables default GitHub token

      - name: Set Git Config
        run: |
          git config --global user.name "arjunchadda1"
          git config --global user.email "arjunchadda93545@gmail.com"

      - name: Make Dummy Commits
        run: |
          for i in {1..4}; do
            echo "Commit $i on $(date)" >> contribution_log.txt
            git add .
            git commit -m "Automated commit $i on $(date)"
            sleep 3  # Space out commits
          done

      - name: Push Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's built-in token
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
